### PR TITLE
delete needless fields,  getter, and callers in tests

### PR DESCRIPTION
**Pull request by shiraki-y**

### CODE REVIEW

**Comment by justinian336** [comment]
以下のも確認する必要がある：
- https://github.com/gyro-n/gopay-java-sdk/blob/4c09c872639c70ff69a6140618b042a1e8560038/src/test/java/jp/gopay/sdk/builders/batch_charge/BatchCreateChargeTest.java

- https://github.com/gyro-n/gopay-java-sdk/blob/312b50b221e38c660b5c542e6fdf35a4d2f6b262/src/test/java/jp/gopay/sdk/utils/requestsAndResponses/ChargesFakeRR.java

**Comment by shiraki-y** [comment]
I'v done the additional modification.

**Comment by justinian336** [comment]
Can you please also delete the unnecessary field here? https://github.com/gyro-n/gopay-java-sdk/blob/55045c239532e2ec65bc3fb1d0b772eda8edf9ed/src/test/java/jp/gopay/sdk/bankaccount/UpdateBankAccountTest.java#L33

**Comment by shiraki-y** [comment]
I'v deleted the unnecessary field in `UpdateBankAccountTest.java`.

**Pull request merged**
